export default [
  {
    title: '商品上下架',
    authKeys: [''],
    icon: require('@/assets/img/menu/newflag.png'),
    menuKey: 'shelve',
    group: 'distribution',
    path: '/shelve',
  },
  {
    title: '负数单管理',
    authKeys: [''],
    icon: require('@/assets/img/menu/newflag.png'),
    menuKey: 'negative',
    group: 'distribution',
    path: '/negative',
  },
  {
    title: '企业管理',
    authKeys: [''],
    icon: require('@/assets/img/menu/newflag.png'),
    menuKey: 'company',
    group: 'distribution',
    path: '/company',
  },
  {
    title: '账号管理',
    authKeys: [''],
    icon: require('@/assets/img/menu/newflag.png'),
    menuKey: 'account',
    group: 'distribution',
    path: '/account',
  },
  {
    title: '供应商',
    icon: require('@/assets/img/menu/icon_afterSales.png'),
    menuKey: 'supplier',
    group: 'distribution',
    path: '/supplier',
  },
  {
    title: '销售单管理',
    icon: require('@/assets/img/menu/icon_afterSales.png'),
    menuKey: 'market',
    group: 'distribution',
    path: '/market',
  },
  {
    title: "商品管理",
    icon: require("@/assets/img/menu/icon_afterSales.png"),
    menuKey: "market",
    group: "distribution",
    path: "/commodity",
  },
];
