export default [
  {
    title: '企业管理',
    authKeys: [''],
    icon: require('@/assets/img/menu/icon_account.png'),
    menuKey: 'company',
    group: 'distribution',
    path: '/company',
  },
  {
    title: '账号管理',
    authKeys: [''],
    icon: require('@/assets/img/menu/icon_account.png'),
    menuKey: 'account',
    group: 'distribution',
    path: '/account',
  },
  {
    title: '供应商管理',
    icon: require('@/assets/img/menu/icon_supplier.png'),
    menuKey: 'supplier',
    group: 'distribution',
    path: '/supplier',
  },
  {
    title: '商品品类管理',
    icon: require('@/assets/img/menu/icon_order.png'),
    menuKey: 'category',
    group: 'distribution',
    path: '/category',
  },
  {
    title: '商品管理',
    icon: require('@/assets/img/menu/icon_transaction.png'),
    menuKey: 'market',
    group: 'distribution',
    path: '/commodity',
  },
  {
    title: '商品上下架',
    authKeys: [''],
    icon: require('@/assets/img/menu/icon_order.png'),
    menuKey: 'shelve',
    group: 'distribution',
    path: '/shelve',
  },
  {
    title: '销售单管理',
    icon: require('@/assets/img/menu/icon_order.png'),
    menuKey: 'market',
    group: 'distribution',
    path: '/market',
  },
  {
    title: '负数单管理',
    authKeys: [''],
    icon: require('@/assets/img/menu/icon_order.png'),
    menuKey: 'negative',
    group: 'distribution',
    path: '/negative',
  },
]
