export default [
	{
		title: "账号列表",
		authKeys: [""],
		icon: require("@/assets/img/menu/icon_account.png"),
		menuKey: "accountList",
		group: "distribution",
		path: "/accountList",
	},
	{
		title: "账号角色",
		authKeys: [""],
		icon: require("@/assets/img/menu/icon_account.png"),
		menuKey: "accountRole",
		group: "distribution",
		path: "/accountRole",
	},
	{
		title: "采购单管理",
		authKeys: [""],
		icon: require("@/assets/img/menu/icon_account.png"),
		menuKey: "marketList",
		group: "distribution",
		path: "/marketList",
	},
	{
		title: "应收单管理",
		authKeys: [""],
		icon: require("@/assets/img/menu/icon_tanchuang.png"),
		menuKey: "collectionList",
		group: "distribution",
		path: "/collectionList",
	},

	{
		title: "应付单管理",
		authKeys: [""],
		icon: require("@/assets/img/menu/icon_supplier.png"),
		menuKey: "paymentList",
		group: "distribution",
		path: "/paymentList",
	},
	{
		title: "请款单列表",
		// authKeys: [""],
		icon: require("@/assets/img/menu/icon_supplier.png"),
		menuKey: "cashRequirement",
		group: "distribution",
		path: "/cashRequirement",
	},
	{
		title: "发票管理列表",
		// authKeys: [""],
		icon: require("@/assets/img/menu/icon_transaction.png"),
		menuKey: "invoice",
		group: "distribution",
		path: "/invoice",
	},
	{
		title: "订单列表",
		authKeys: [""],
		icon: require("@/assets/img/menu/icon_order.png"),
		menuKey: "orderManagement",
		group: "distribution",
		path: "/orderManagement",
	},
	{
		title: "售后列表",
		authKeys: [""],
		icon: require("@/assets/img/menu/icon_order.png"),
		menuKey: "orderAfterSaleList",
		group: "distribution",
		path: "/orderAfterSaleList",
	},
	{
		title: "案场采购-售后申请",
		authKeys: [""],
		icon: require("@/assets/img/menu/icon_afterSales.png"),
		menuKey: "afterSale",
		group: "distribution",
		path: "/afterSale",
	},
	{
		title: "供应商",
		icon: require("@/assets/img/menu/icon_afterSales.png"),
		menuKey: "supplier",
		group: "distribution",
		path: "/supplier",
	},
	{
		title: "销售单管理",
		icon: require("@/assets/img/menu/icon_afterSales.png"),
		menuKey: "market",
		group: "distribution",
		path: "/market",
	},
];
